# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    #http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_lifetime: 172800
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    # Reverse proxy support
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']

    #esi: true
    #fragments: true
    php_errors:
        log: true

    validation: { enable_annotations: true }

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
