framework:
    default_locale: '%env(LOCALE)%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        enabled_locales: ['en_US', 'fr_FR']
        fallbacks: ['en_US']
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
