core_routes:
    resource: "@HedgebotCoreBundle/Controller/"
    type:     annotation

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /dashboard
        permanent: true

plugins_routes:
    prefix: /plugin
    resource: .
    type: plugin_routes

plugins_public_routes:
    prefix: /public/plugin
    resource: .
    type: plugin_public_routes

logout:
    path: /logout